C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py
C:/Users/sstic/miniconda/envs/allinone/python.exe c:/Personal/Developed/Hailuio/Gemni_img.py